GameConsole.delete_all
GameConsole.create(:id=>1,:short_code=>"ps4",:name=>"Sony Playstation 4",:tier=>1,:visible=>true)
GameConsole.create(:id=>2,:short_code=>"ps3",:name=>"Sony Playstation 3",:tier=>2,:visible=>true)
GameConsole.create(:id=>3,:short_code=>"ps2",:name=>"Sony Playstation 2",:tier=>3,:visible=>false)
GameConsole.create(:id=>4,:short_code=>"ps1",:name=>"Sony Playstation",:tier=>3,:visible=>false)
GameConsole.create(:id=>5,:short_code=>"wiiu",:name=>"Nintendo Wii U",:tier=>1,:visible=>true)
GameConsole.create(:id=>6,:short_code=>"wii",:name=>"Nintendo Wii",:tier=>2,:visible=>true)
GameConsole.create(:id=>7,:short_code=>"gamecube",:name=>"Nintendo GameCube",:tier=>3,:visible=>false)
GameConsole.create(:id=>8,:short_code=>"nintendo64",:name=>"Nintendo 64",:tier=>3,:visible=>false)
GameConsole.create(:id=>9,:short_code=>"snes",:name=>"Super Nintendo Entertainment System",:tier=>3,:visible=>false)
GameConsole.create(:id=>10,:short_code=>"nes",:name=>"Nintendo Entertainment System",:tier=>3,:visible=>false)
GameConsole.create(:id=>11,:short_code=>"xbox-one",:name=>"Microsoft Xbox One",:tier=>1,:visible=>true)
GameConsole.create(:id=>12,:short_code=>"xbox-360",:name=>"Microsoft Xbox 360",:tier=>2,:visible=>true)
GameConsole.create(:id=>13,:short_code=>"xbox",:name=>"Microsoft Xbox",:tier=>3,:visible=>false)
GameConsole.create(:id=>14,:short_code=>"dreamcast",:name=>"Sega Dreamcast",:tier=>3,:visible=>false)
GameConsole.create(:id=>15,:short_code=>"saturn",:name=>"Sega Saturn",:tier=>3,:visible=>false)
GameConsole.create(:id=>16,:short_code=>"genesis",:name=>"Sega Genesis",:tier=>3,:visible=>false)
